language: node_js
install:
  - npm install stylus -g
  - npm install pug-cli -g
  - npm install uglifyjs -g
script: make
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: dist
