language: node_js
node_js:
  - 13
install:
  - npm install stylus -g
  - npm install pug-cli -g
  - npm install uglify-es -g
jobs:
  include:
    - stage: deploy
      script: make
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
          tags: true
        local_dir: dist
    - stage: deploy pretty
      script: make pretty
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        on:
          branch: master
          tags: true
